const dialog=document.querySelector('#brief');
document.querySelector('#open-brief').addEventListener('click',()=>dialog.showModal());
document.querySelector('#close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
function updateBrief(){const summary=`Olá, Guilherme! Quero conversar sobre uma landing page.\n\nMeu negócio: ${document.querySelector('#business').value.trim()}\nObjetivo: ${document.querySelector('#objective').value}\nDetalhes: ${document.querySelector('#message').value.trim()||'A definir na conversa.'}`;document.querySelector('#summary').value=summary;document.querySelector('#send-whatsapp').href='https://wa.me/5511997077994?text='+encodeURIComponent(summary);document.querySelector('#send-email').href='mailto:guilherme.fmouradev@outlook.com?subject='+encodeURIComponent('Orçamento de landing page')+'&body='+encodeURIComponent(summary)}
document.querySelector('#brief-form').addEventListener('submit',e=>{e.preventDefault();updateBrief();document.querySelector('#brief-result').hidden=false;document.querySelector('#summary').focus();document.querySelector('#summary').select()});
document.querySelector('#brief-form').addEventListener('input',()=>{if(!document.querySelector('#brief-result').hidden)updateBrief()});

const slides=[...document.querySelectorAll('.feature-slide')];const dots=[...document.querySelectorAll('[data-slide]')];const descriptions=['Identidade marcante. Serviços claros.<br>Um caminho simples até o agendamento.','Veículos em destaque. Catálogo interativo.<br>Uma vitrine para novas possibilidades.','Cuidado em cada detalhe. Visual acolhedor.<br>Uma experiência para conhecer a clínica.'];let currentSlide=0;function showSlide(index){currentSlide=(index+slides.length)%slides.length;slides.forEach((slide,i)=>slide.hidden=i!==currentSlide);dots.forEach((dot,i)=>{dot.classList.toggle('active',i===currentSlide);if(i===currentSlide)dot.setAttribute('aria-current','true');else dot.removeAttribute('aria-current')});document.querySelector('#feature-count').textContent=String(currentSlide+1).padStart(2,'0')+' / 03';document.querySelector('#feature-description').innerHTML=descriptions[currentSlide]}document.querySelector('#feature-prev').addEventListener('click',()=>showSlide(currentSlide-1));document.querySelector('#feature-next').addEventListener('click',()=>showSlide(currentSlide+1));dots.forEach(dot=>dot.addEventListener('click',()=>showSlide(Number(dot.dataset.slide))));document.querySelector('.carousel-controls').addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();showSlide(currentSlide+(e.key==='ArrowRight'?1:-1))}});let touchStart=null;const slideArea=document.querySelector('.feature-slides');slideArea.addEventListener('touchstart',e=>{touchStart=e.touches[0].clientX},{passive:true});slideArea.addEventListener('touchend',e=>{if(touchStart!==null){const distance=e.changedTouches[0].clientX-touchStart;if(Math.abs(distance)>50)showSlide(currentSlide+(distance<0?1:-1));touchStart=null}},{passive:true});
